---

- hosts: all
  become: true
  tasks:

   - name: install apache and php
     package:
        name:
          - "{{ apache_package }}" #the value is defined in the inventory file
          - "{{ php_package }}"
        state: latest
        update_cache: yes
